name: example
description: یک پروژه نمونه برای نمایش قابلیت‌های پکیج قدرتمند quantum_list.
publish_to: 'none' # به pub.dev اعلام می‌کند که این پروژه نمونه را منتشر نکند.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # این بخش مهم‌ترین قسمت است
  # به پروژه می‌گوید که پکیج را از پوشه والد (../) بخواند
  quantum_list:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
